package com.jasonko.movietime.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.jasonko.movietime.dao.RecentMovie;
import com.jasonko.movietime.dao.FollowMovie;

import com.jasonko.movietime.dao.RecentMovieDao;
import com.jasonko.movietime.dao.FollowMovieDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recentMovieDaoConfig;
    private final DaoConfig followMovieDaoConfig;

    private final RecentMovieDao recentMovieDao;
    private final FollowMovieDao followMovieDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recentMovieDaoConfig = daoConfigMap.get(RecentMovieDao.class).clone();
        recentMovieDaoConfig.initIdentityScope(type);

        followMovieDaoConfig = daoConfigMap.get(FollowMovieDao.class).clone();
        followMovieDaoConfig.initIdentityScope(type);

        recentMovieDao = new RecentMovieDao(recentMovieDaoConfig, this);
        followMovieDao = new FollowMovieDao(followMovieDaoConfig, this);

        registerDao(RecentMovie.class, recentMovieDao);
        registerDao(FollowMovie.class, followMovieDao);
    }
    
    public void clear() {
        recentMovieDaoConfig.getIdentityScope().clear();
        followMovieDaoConfig.getIdentityScope().clear();
    }

    public RecentMovieDao getRecentMovieDao() {
        return recentMovieDao;
    }

    public FollowMovieDao getFollowMovieDao() {
        return followMovieDao;
    }

}
