package com.jasonko.movietime.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.jasonko.movietime.dao.FollowMovie;
import com.jasonko.movietime.dao.FavoriteTheater;
import com.jasonko.movietime.dao.FavoriteMessage;
import com.jasonko.movietime.dao.FavoriteReply;

import com.jasonko.movietime.dao.FollowMovieDao;
import com.jasonko.movietime.dao.FavoriteTheaterDao;
import com.jasonko.movietime.dao.FavoriteMessageDao;
import com.jasonko.movietime.dao.FavoriteReplyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig followMovieDaoConfig;
    private final DaoConfig favoriteTheaterDaoConfig;
    private final DaoConfig favoriteMessageDaoConfig;
    private final DaoConfig favoriteReplyDaoConfig;

    private final FollowMovieDao followMovieDao;
    private final FavoriteTheaterDao favoriteTheaterDao;
    private final FavoriteMessageDao favoriteMessageDao;
    private final FavoriteReplyDao favoriteReplyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        followMovieDaoConfig = daoConfigMap.get(FollowMovieDao.class).clone();
        followMovieDaoConfig.initIdentityScope(type);

        favoriteTheaterDaoConfig = daoConfigMap.get(FavoriteTheaterDao.class).clone();
        favoriteTheaterDaoConfig.initIdentityScope(type);

        favoriteMessageDaoConfig = daoConfigMap.get(FavoriteMessageDao.class).clone();
        favoriteMessageDaoConfig.initIdentityScope(type);

        favoriteReplyDaoConfig = daoConfigMap.get(FavoriteReplyDao.class).clone();
        favoriteReplyDaoConfig.initIdentityScope(type);

        followMovieDao = new FollowMovieDao(followMovieDaoConfig, this);
        favoriteTheaterDao = new FavoriteTheaterDao(favoriteTheaterDaoConfig, this);
        favoriteMessageDao = new FavoriteMessageDao(favoriteMessageDaoConfig, this);
        favoriteReplyDao = new FavoriteReplyDao(favoriteReplyDaoConfig, this);

        registerDao(FollowMovie.class, followMovieDao);
        registerDao(FavoriteTheater.class, favoriteTheaterDao);
        registerDao(FavoriteMessage.class, favoriteMessageDao);
        registerDao(FavoriteReply.class, favoriteReplyDao);
    }
    
    public void clear() {
        followMovieDaoConfig.getIdentityScope().clear();
        favoriteTheaterDaoConfig.getIdentityScope().clear();
        favoriteMessageDaoConfig.getIdentityScope().clear();
        favoriteReplyDaoConfig.getIdentityScope().clear();
    }

    public FollowMovieDao getFollowMovieDao() {
        return followMovieDao;
    }

    public FavoriteTheaterDao getFavoriteTheaterDao() {
        return favoriteTheaterDao;
    }

    public FavoriteMessageDao getFavoriteMessageDao() {
        return favoriteMessageDao;
    }

    public FavoriteReplyDao getFavoriteReplyDao() {
        return favoriteReplyDao;
    }

}
