package com.jasonko.movietime.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FAVORITE_REPLY.
 */
public class FavoriteReply {

    private Long id;
    private int reply_id;
    private int message_id;
    /** Not-null value. */
    private String author;
    /** Not-null value. */
    private String content;
    /** Not-null value. */
    private String pub_date;
    private int head_index;
    private int like_count;

    public FavoriteReply() {
    }

    public FavoriteReply(Long id) {
        this.id = id;
    }

    public FavoriteReply(Long id, int reply_id, int message_id, String author, String content, String pub_date, int head_index, int like_count) {
        this.id = id;
        this.reply_id = reply_id;
        this.message_id = message_id;
        this.author = author;
        this.content = content;
        this.pub_date = pub_date;
        this.head_index = head_index;
        this.like_count = like_count;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getReply_id() {
        return reply_id;
    }

    public void setReply_id(int reply_id) {
        this.reply_id = reply_id;
    }

    public int getMessage_id() {
        return message_id;
    }

    public void setMessage_id(int message_id) {
        this.message_id = message_id;
    }

    /** Not-null value. */
    public String getAuthor() {
        return author;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAuthor(String author) {
        this.author = author;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    /** Not-null value. */
    public String getPub_date() {
        return pub_date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPub_date(String pub_date) {
        this.pub_date = pub_date;
    }

    public int getHead_index() {
        return head_index;
    }

    public void setHead_index(int head_index) {
        this.head_index = head_index;
    }

    public int getLike_count() {
        return like_count;
    }

    public void setLike_count(int like_count) {
        this.like_count = like_count;
    }

}
