package com.jasonko.movietime.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.jasonko.movietime.dao.FavoriteReply;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FAVORITE_REPLY.
*/
public class FavoriteReplyDao extends AbstractDao<FavoriteReply, Long> {

    public static final String TABLENAME = "FAVORITE_REPLY";

    /**
     * Properties of entity FavoriteReply.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Reply_id = new Property(1, int.class, "reply_id", false, "REPLY_ID");
        public final static Property Message_id = new Property(2, int.class, "message_id", false, "MESSAGE_ID");
        public final static Property Author = new Property(3, String.class, "author", false, "AUTHOR");
        public final static Property Content = new Property(4, String.class, "content", false, "CONTENT");
        public final static Property Pub_date = new Property(5, String.class, "pub_date", false, "PUB_DATE");
        public final static Property Head_index = new Property(6, int.class, "head_index", false, "HEAD_INDEX");
        public final static Property Like_count = new Property(7, int.class, "like_count", false, "LIKE_COUNT");
    };


    public FavoriteReplyDao(DaoConfig config) {
        super(config);
    }
    
    public FavoriteReplyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'FAVORITE_REPLY' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'REPLY_ID' INTEGER NOT NULL ," + // 1: reply_id
                "'MESSAGE_ID' INTEGER NOT NULL ," + // 2: message_id
                "'AUTHOR' TEXT NOT NULL ," + // 3: author
                "'CONTENT' TEXT NOT NULL ," + // 4: content
                "'PUB_DATE' TEXT NOT NULL ," + // 5: pub_date
                "'HEAD_INDEX' INTEGER NOT NULL ," + // 6: head_index
                "'LIKE_COUNT' INTEGER NOT NULL );"); // 7: like_count
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FAVORITE_REPLY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FavoriteReply entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getReply_id());
        stmt.bindLong(3, entity.getMessage_id());
        stmt.bindString(4, entity.getAuthor());
        stmt.bindString(5, entity.getContent());
        stmt.bindString(6, entity.getPub_date());
        stmt.bindLong(7, entity.getHead_index());
        stmt.bindLong(8, entity.getLike_count());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FavoriteReply readEntity(Cursor cursor, int offset) {
        FavoriteReply entity = new FavoriteReply( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // reply_id
            cursor.getInt(offset + 2), // message_id
            cursor.getString(offset + 3), // author
            cursor.getString(offset + 4), // content
            cursor.getString(offset + 5), // pub_date
            cursor.getInt(offset + 6), // head_index
            cursor.getInt(offset + 7) // like_count
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FavoriteReply entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setReply_id(cursor.getInt(offset + 1));
        entity.setMessage_id(cursor.getInt(offset + 2));
        entity.setAuthor(cursor.getString(offset + 3));
        entity.setContent(cursor.getString(offset + 4));
        entity.setPub_date(cursor.getString(offset + 5));
        entity.setHead_index(cursor.getInt(offset + 6));
        entity.setLike_count(cursor.getInt(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(FavoriteReply entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(FavoriteReply entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
