package com.jasonko.movietime.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table FAVORITE_MESSAGE.
 */
public class FavoriteMessage implements Serializable {

    private Long id;
    private int message_id;
    /** Not-null value. */
    private String author;
    /** Not-null value. */
    private String title;
    /** Not-null value. */
    private String tag;
    /** Not-null value. */
    private String content;
    /** Not-null value. */
    private String pub_date;
    private int view_count;
    private int like_count;
    private int reply_size;
    private int head_index;
    private boolean is_head;
    /** Not-null value. */
    private String link_url;

    public FavoriteMessage() {
    }

    public FavoriteMessage(Long id) {
        this.id = id;
    }

    public FavoriteMessage(Long id, int message_id, String author, String title, String tag, String content, String pub_date, int view_count, int like_count, int reply_size, int head_index, boolean is_head, String link_url) {
        this.id = id;
        this.message_id = message_id;
        this.author = author;
        this.title = title;
        this.tag = tag;
        this.content = content;
        this.pub_date = pub_date;
        this.view_count = view_count;
        this.like_count = like_count;
        this.reply_size = reply_size;
        this.head_index = head_index;
        this.is_head = is_head;
        this.link_url = link_url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getMessage_id() {
        return message_id;
    }

    public void setMessage_id(int message_id) {
        this.message_id = message_id;
    }

    /** Not-null value. */
    public String getAuthor() {
        return author;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAuthor(String author) {
        this.author = author;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    /** Not-null value. */
    public String getTag() {
        return tag;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    /** Not-null value. */
    public String getPub_date() {
        return pub_date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPub_date(String pub_date) {
        this.pub_date = pub_date;
    }

    public int getView_count() {
        return view_count;
    }

    public void setView_count(int view_count) {
        this.view_count = view_count;
    }

    public int getLike_count() {
        return like_count;
    }

    public void setLike_count(int like_count) {
        this.like_count = like_count;
    }

    public int getReply_size() {
        return reply_size;
    }

    public void setReply_size(int reply_size) {
        this.reply_size = reply_size;
    }

    public int getHead_index() {
        return head_index;
    }

    public void setHead_index(int head_index) {
        this.head_index = head_index;
    }

    public boolean getIs_head() {
        return is_head;
    }

    public void setIs_head(boolean is_head) {
        this.is_head = is_head;
    }

    /** Not-null value. */
    public String getLink_url() {
        return link_url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLink_url(String link_url) {
        this.link_url = link_url;
    }

}
