package com.jasonko.movietime.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.jasonko.movietime.dao.FollowMovie;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FOLLOW_MOVIE.
*/
public class FollowMovieDao extends AbstractDao<FollowMovie, Long> {

    public static final String TABLENAME = "FOLLOW_MOVIE";

    /**
     * Properties of entity FollowMovie.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Movie_class = new Property(2, String.class, "movie_class", false, "MOVIE_CLASS");
        public final static Property Small_pic = new Property(3, String.class, "small_pic", false, "SMALL_PIC");
        public final static Property Movie_id = new Property(4, int.class, "movie_id", false, "MOVIE_ID");
        public final static Property Publish_day = new Property(5, java.util.Date.class, "publish_day", false, "PUBLISH_DAY");
        public final static Property Update_date = new Property(6, java.util.Date.class, "update_date", false, "UPDATE_DATE");
    };


    public FollowMovieDao(DaoConfig config) {
        super(config);
    }
    
    public FollowMovieDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'FOLLOW_MOVIE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'TITLE' TEXT NOT NULL ," + // 1: title
                "'MOVIE_CLASS' TEXT NOT NULL ," + // 2: movie_class
                "'SMALL_PIC' TEXT NOT NULL ," + // 3: small_pic
                "'MOVIE_ID' INTEGER NOT NULL ," + // 4: movie_id
                "'PUBLISH_DAY' INTEGER NOT NULL ," + // 5: publish_day
                "'UPDATE_DATE' INTEGER NOT NULL );"); // 6: update_date
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FOLLOW_MOVIE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FollowMovie entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTitle());
        stmt.bindString(3, entity.getMovie_class());
        stmt.bindString(4, entity.getSmall_pic());
        stmt.bindLong(5, entity.getMovie_id());
        stmt.bindLong(6, entity.getPublish_day().getTime());
        stmt.bindLong(7, entity.getUpdate_date().getTime());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FollowMovie readEntity(Cursor cursor, int offset) {
        FollowMovie entity = new FollowMovie( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // title
            cursor.getString(offset + 2), // movie_class
            cursor.getString(offset + 3), // small_pic
            cursor.getInt(offset + 4), // movie_id
            new java.util.Date(cursor.getLong(offset + 5)), // publish_day
            new java.util.Date(cursor.getLong(offset + 6)) // update_date
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FollowMovie entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.getString(offset + 1));
        entity.setMovie_class(cursor.getString(offset + 2));
        entity.setSmall_pic(cursor.getString(offset + 3));
        entity.setMovie_id(cursor.getInt(offset + 4));
        entity.setPublish_day(new java.util.Date(cursor.getLong(offset + 5)));
        entity.setUpdate_date(new java.util.Date(cursor.getLong(offset + 6)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(FollowMovie entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(FollowMovie entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
