package com.jasonko.movietime.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RECENT_MOVIE.
 */
public class RecentMovie {

    private Long id;
    /** Not-null value. */
    private String title;
    /** Not-null value. */
    private String movie_class;
    /** Not-null value. */
    private String movie_type;
    /** Not-null value. */
    private String actors;
    /** Not-null value. */
    private String publish_date;
    /** Not-null value. */
    private String small_pic;
    private int movie_id;
    /** Not-null value. */
    private java.util.Date update_date;

    public RecentMovie() {
    }

    public RecentMovie(Long id) {
        this.id = id;
    }

    public RecentMovie(Long id, String title, String movie_class, String movie_type, String actors, String publish_date, String small_pic, int movie_id, java.util.Date update_date) {
        this.id = id;
        this.title = title;
        this.movie_class = movie_class;
        this.movie_type = movie_type;
        this.actors = actors;
        this.publish_date = publish_date;
        this.small_pic = small_pic;
        this.movie_id = movie_id;
        this.update_date = update_date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    /** Not-null value. */
    public String getMovie_class() {
        return movie_class;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMovie_class(String movie_class) {
        this.movie_class = movie_class;
    }

    /** Not-null value. */
    public String getMovie_type() {
        return movie_type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMovie_type(String movie_type) {
        this.movie_type = movie_type;
    }

    /** Not-null value. */
    public String getActors() {
        return actors;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setActors(String actors) {
        this.actors = actors;
    }

    /** Not-null value. */
    public String getPublish_date() {
        return publish_date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPublish_date(String publish_date) {
        this.publish_date = publish_date;
    }

    /** Not-null value. */
    public String getSmall_pic() {
        return small_pic;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSmall_pic(String small_pic) {
        this.small_pic = small_pic;
    }

    public int getMovie_id() {
        return movie_id;
    }

    public void setMovie_id(int movie_id) {
        this.movie_id = movie_id;
    }

    /** Not-null value. */
    public java.util.Date getUpdate_date() {
        return update_date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdate_date(java.util.Date update_date) {
        this.update_date = update_date;
    }

}
